# Generated by Django 6.0.3 on 2026-03-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anki_last_checked',
            field=models.DateTimeField(blank=True, help_text='Last time Anki connection was verified', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='anki_setup_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed Anki desktop + AnkiConnect setup'),
        ),
        migrations.AddField(
            model_name='user',
            name='ankiconnect_version',
            field=models.IntegerField(blank=True, help_text='Detected AnkiConnect version number', null=True),
        ),
    ]
