# Generated by Django 6.0.3 on 2026-03-10 13:54

import django.utils.timezone
import uuid
from django.db import migrations, models


def generate_verification_tokens(apps, schema_editor):
    """Generate unique verification tokens for existing users"""
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.verification_token = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_anki_last_checked_user_anki_setup_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether user has verified their email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used for email verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the verification token was created'),
            preserve_default=False,
        ),
        migrations.RunPython(generate_verification_tokens, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token used for email verification', unique=True),
        ),
    ]
