# Generated by Django 6.0.3 on 2026-03-05 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0002_alter_language_options_language_azure_tts_locale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField(help_text='Raw vocabulary input from user, one word/phrase per line')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('translating', 'Translating'), ('generating_tts', 'Generating TTS'), ('pushing_to_anki', 'Pushing to Anki'), ('completed', 'Completed'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('explanation_language', models.ForeignKey(help_text='The language used for explanations', on_delete=django.db.models.deletion.CASCADE, related_name='explanation_batches', to='languages.language')),
                ('target_language', models.ForeignKey(help_text='The language being learned', on_delete=django.db.models.deletion.CASCADE, related_name='target_batches', to='languages.language')),
                ('user', models.ForeignKey(help_text='The user who submitted this batch', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vocabulary Batch',
                'verbose_name_plural': 'Vocabulary Batches',
                'db_table': 'vocabulary_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(help_text='Original vocabulary input, e.g. de la pomme', max_length=500)),
                ('target_word', models.CharField(blank=True, default='', help_text='Word in target language (Français field)', max_length=500)),
                ('explanation_word', models.CharField(blank=True, default='', help_text='Translation/explanation (English field)', max_length=500)),
                ('synonyme', models.TextField(blank=True, default='', help_text='Synonyms in target language')),
                ('conjugaison_genre', models.TextField(blank=True, default='', help_text='Conjugation tables or gender information')),
                ('audio_file', models.FileField(blank=True, help_text='TTS audio of the target word', null=True, upload_to='tts/words/')),
                ('exemple_target', models.TextField(blank=True, default='', help_text='Example sentence in target language')),
                ('exemple_explanation', models.TextField(blank=True, default='', help_text='Example sentence translation')),
                ('exemple1_audio', models.FileField(blank=True, help_text='TTS audio of example sentence 1', null=True, upload_to='tts/examples/')),
                ('exemple2_target', models.TextField(blank=True, default='', help_text='Second example in target language')),
                ('exemple2_explanation', models.TextField(blank=True, default='', help_text='Second example translation')),
                ('exemple2_audio', models.FileField(blank=True, help_text='TTS audio of example sentence 2', null=True, upload_to='tts/examples/')),
                ('extend', models.TextField(blank=True, default='', help_text='Additional notes, usage, cultural context')),
                ('hint', models.TextField(blank=True, default='', help_text='Memory hint or mnemonic')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('translated', 'Translated'), ('tts_done', 'TTS Done'), ('pushed', 'Pushed to Anki'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('anki_note_id', models.BigIntegerField(blank=True, help_text='Note ID returned by AnkiConnect after successful push', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if card processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='The batch this card belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.vocabularybatch')),
            ],
            options={
                'verbose_name': 'Vocabulary Card',
                'verbose_name_plural': 'Vocabulary Cards',
                'db_table': 'vocabulary_cards',
                'ordering': ['id'],
            },
        ),
    ]
