# Generated by Django 6.0.3 on 2026-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularybatch',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Global error message if the whole batch fails'),
        ),
    ]
