# Generated by Django 6.0.3 on 2026-03-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='language',
            name='azure_tts_locale',
            field=models.CharField(blank=True, default='', help_text='Azure TTS locale, e.g. fr-FR', max_length=20),
        ),
        migrations.AddField(
            model_name='language',
            name='azure_tts_voice',
            field=models.CharField(blank=True, default='', help_text='Azure TTS voice, e.g. fr-FR-DeniseNeural', max_length=255),
        ),
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this language is available for selection'),
        ),
        migrations.AddField(
            model_name='language',
            name='native_name',
            field=models.CharField(blank=True, default='', help_text='Name in native script, e.g. Français', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(help_text='ISO 639-1 code, e.g. fr', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Display name, e.g. French', max_length=100),
        ),
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anki_model_name', models.CharField(help_text='Anki note type name, e.g. French Vocabulary', max_length=255)),
                ('default_deck_name', models.CharField(help_text='Default Anki deck name, e.g. French::Vocabulary', max_length=255)),
                ('fields_definition', models.JSONField(default=list, help_text='Ordered list of Anki note field names as JSON array')),
                ('llm_prompt_template', models.TextField(blank=True, default='', help_text='Prompt template for LLM. Use {input_text}, {target_lang}, {explanation_lang}')),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_template', to='languages.language')),
            ],
            options={
                'db_table': 'card_templates',
            },
        ),
    ]
