# Generated by Django 6.0.3 on 2026-03-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_alter_language_options_language_azure_tts_locale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='vocab_label',
            field=models.CharField(blank=True, default='Vocabulary', help_text='Label to use for vocabulary decks (e.g. "Vocabulary" or localized word)', max_length=100),
        ),
    ]
