# Generated by Django 6.0.3 on 2026-03-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_language_vocab_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='back_template',
            field=models.TextField(blank=True, default='{{FrontSide}}\n\n<hr id=answer>\n\n{{English}}', help_text='Anki card back template (afmt)'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='css_style',
            field=models.TextField(blank=True, default='.card { font-family: arial; font-size: 20px; text-align: center; color: black; background-color: white; }', help_text='Anki card CSS styling'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='front_template',
            field=models.TextField(blank=True, default='{{Français}}', help_text='Anki card front template (qfmt)'),
        ),
    ]
