# Generated by Django 6.0.3 on 2026-03-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_cardtemplate_back_template_cardtemplate_css_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='back_template_card2',
            field=models.TextField(blank=True, default='{{FrontSide}}\n\n<hr id=answer>\n\n{{TARGET_LANGUAGE}}', help_text='Anki card 2 (Listening/Spelling) back template (afmt2)'),
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='front_template_card2',
            field=models.TextField(blank=True, default='{{Audio}}', help_text='Anki card 2 (Listening/Spelling) front template (qfmt2)'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='css_style',
            field=models.TextField(blank=True, default=".card {\n    font-family: 'Segoe UI', 'Microsoft YaHei', '微軟正黑體', Arial, sans-serif;\n    font-size: 20px;\n    text-align: center;\n    color: #2c3e50;\n    background-color: #ffffff;\n    padding: 0;\n    line-height: 1.6;\n}\n\n/* Title Bar Styling */\n.TitleBar {\n    padding: 10px;\n    font-weight: bold;\n    font-size: 16px;\n    border-radius: 8px 8px 0 0;\n    margin-bottom: 10px;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n}\n\n.title-r {\n    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n    color: white;\n}\n\n.title-l {\n    background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);\n    color: white;\n}\n\n/* Tags */\n.Tag {\n    padding: 8px;\n    font-size: 12px;\n    margin-bottom: 15px;\n}\n\n.light-r {\n    background-color: #e8eaf6;\n    color: #5c6bc0;\n    border-radius: 4px;\n}\n\n/* Text Card Styling */\n.Text_Card {\n    background-color: #fafafa;\n    padding: 20px;\n    margin: 10px;\n}\n\n.radius {\n    border-radius: 8px;\n    box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n}\n\n.Text_big {\n    font-size: 36px;\n    font-weight: bold;\n    color: #1a237e;\n    margin: 20px 0;\n}\n\n.Text-answer {\n    font-size: 28px;\n    color: #2e7d32;\n    margin: 15px 0;\n    font-weight: 600;\n}\n\n/* Grammar/Verb Form */\n.Verbform {\n    font-size: 16px;\n    color: #757575;\n    font-style: italic;\n    margin: 10px 0;\n}\n\n/* Gender-specific styling */\n.feminine {\n    border-left: 5px solid #e91e63;\n    padding-left: 15px;\n}\n\n.masculine {\n    border-left: 5px solid #2196f3;\n    padding-left: 15px;\n}\n\n.neuter {\n    border-left: 5px solid #4caf50;\n    padding-left: 15px;\n}\n\n/* Examples List */\n.light-r2 {\n    background-color: #f5f5f5;\n    border-radius: 8px;\n    padding: 15px 30px;\n    margin: 15px 10px;\n    text-align: left;\n    list-style: none;\n}\n\n.eB {\n    font-size: 18px;\n    color: #1976d2;\n    font-weight: 500;\n    margin: 10px 0;\n    padding: 8px;\n    background-color: #e3f2fd;\n    border-radius: 4px;\n}\n\n.eg {\n    font-size: 16px;\n    color: #616161;\n    margin: 5px 0 15px 20px;\n    font-style: italic;\n}\n\n/* Extend/Hint Section */\n.extend {\n    font-size: 14px;\n    color: #6a1b9a;\n    margin: 15px 10px;\n    text-align: left;\n    padding: 12px;\n    background-color: #f3e5f5;\n    border-left: 4px solid #9c27b0;\n    border-radius: 4px;\n}\n\n/* HR Separator */\nhr#answer {\n    border: none;\n    border-top: 3px solid #e0e0e0;\n    margin: 20px 0;\n}\n\n/* Synonyme */\n.card .Synonyme {\n    font-size: 16px;\n    color: #00796b;\n    margin: 10px 0;\n    font-style: italic;\n}\n\n/* No Replay Button */\n.noreplaybutton {\n    display: none;\n}", help_text='Anki card CSS styling'),
        ),
    ]
